### ISSUE TITLE
Space in Message.txt file

### ISSUE THREAD

**Issue by kgbrady** [usnistgov/hit-erx-tool#1]
In context-based, when I click "Load Example", it seems to add a blank line at the end of the message.
This gives the error,"Segment is not expected at this location". When I delete the line the error goes away.
I don't think the line is in the file, but added when it is loaded.

Kevin

**Comment by maxence-lefort** [comment]
I checked two Message.txt in the resource bundle and it looks like there is a blank line at the end of the message. Can you check if you see this blank line in your bundle ?

**Comment by kgbrady** [comment]
Yes it is….Let me check my code

**Comment by fdevaulx-nist** [comment]
removed \n on the last line
